#:schema node_modules/wrangler/config-schema.json
name = "livetiming-mirror-api"
main = "src/index.js"
compatibility_date = "2024-07-18"
compatibility_flags = ["nodejs_compat"]

account_id = "b9261d7f75d36ec3c0ae559737628538"
workers_dev = true

[[routes]]
pattern = "livetiming-mirror.fastf1.dev"
zone_name = "fastf1.dev"
custom_domain = true


[vars]
MAX_CACHE_AGE = "3600"
NOT_FOUND_DELAY = "500"
RATE_LIMIT_REQUESTS_PER_HOUR = "200"
RATE_LIMIT_DELAY = "0"

[[kv_namespaces]]
binding = "RATE_LIMIT"
id = "554dd33886cd420c9f87f079261bef5c"

[[r2_buckets]]
binding = 'LIVETIMING_BUCKET'
bucket_name = 'fastf1-livetiming-mirror'
